version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    image: scaffold-web
    restart: on-failure
    env_file: docker.env
    ports:
      - 80:80
    networks:
      - scaffold-net

networks:
  scaffold-net: